plugins {
    id 'java'
    id "io.qameta.allure" version "2.9.6"
    id "org.gradle.test-retry" version "1.5.3"
}

group = 'org.example'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

allure {
    autoconfigure = true
}

dependencies {
    implementation 'io.qameta.allure:allure-testng:2.23.0'
    implementation 'io.qameta.allure:allure-java-commons:2.23.0'
    implementation 'io.qameta.allure:allure-java-annotations:2.23.0'

    implementation 'org.testng:testng:7.9.0'
    testImplementation 'junit:junit:4.13.2'
    testImplementation 'org.junit.jupiter:junit-jupiter:5.10.0'
    runtimeOnly 'org.aspectj:aspectjweaver:1.9.20'

    implementation 'io.rest-assured:rest-assured:5.4.0'
    implementation 'com.fasterxml.jackson.core:jackson-databind:2.15.2'
    implementation 'org.seleniumhq.selenium:selenium-java:4.14.0'
    implementation 'io.github.bonigarcia:webdrivermanager:5.8.0'
    implementation 'org.projectlombok:lombok:1.18.30'
    implementation 'com.github.javafaker:javafaker:1.0.2'
    implementation 'com.squareup.okhttp3:okhttp:4.11.0'
    implementation 'org.seleniumhq.selenium:selenium-chromium-driver:4.14.0'
}

test {
    useTestNG()
}

tasks.withType(Test).configureEach {
    useTestNG() {
        testLogging {
            events "passed", "skipped", "failed", "standardOut", "standardError"
            exceptionFormat "full"
        }
    }
    systemProperty 'allure.results.directory', 'build/allure-results'
}

task SmokeTestE2e(type: Test) {
    useTestNG() {
        suites 'src/test/resources/testngE2eSmoke.xml'
    }
}

task ApiTest(type: Test) {
    useTestNG() {
        suites 'src/test/resources/testngApi.xml'
    }
}

task ProbeTest(type: Test) {
    useTestNG() {
        suites 'src/test/resources/testngE2eSmokeTesting.xml'
    }
}
